package com.weather.passport.mapper;

import com.weather.passport.model.Donate;
import com.weather.passport.model.DonateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DonateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_donate
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    int countByExample(DonateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_donate
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    int deleteByExample(DonateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_donate
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    int deleteByPrimaryKey(String udid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_donate
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    int insert(Donate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_donate
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    int insertSelective(Donate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_donate
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    List<Donate> selectByExample(DonateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_donate
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    Donate selectByPrimaryKey(String udid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_donate
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    int updateByExampleSelective(@Param("record") Donate record, @Param("example") DonateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_donate
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    int updateByExample(@Param("record") Donate record, @Param("example") DonateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_donate
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    int updateByPrimaryKeySelective(Donate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_donate
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    int updateByPrimaryKey(Donate record);
}