package com.weather.passport.model;

import java.io.Serializable;
import java.util.Date;

public class Donate implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_donate.udid
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    private String udid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_donate.sum
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    private Integer sum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_donate.origin
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    private String origin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_donate.last_order_id
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    private String lastOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_donate.last_donate_time
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    private Date lastDonateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_donate.color_index
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    private Integer colorIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_donate.name
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_donate.city
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_donate
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_donate.udid
     *
     * @return the value of tb_donate.udid
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    public String getUdid() {
        return udid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_donate.udid
     *
     * @param udid the value for tb_donate.udid
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    public void setUdid(String udid) {
        this.udid = udid == null ? null : udid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_donate.sum
     *
     * @return the value of tb_donate.sum
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    public Integer getSum() {
        return sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_donate.sum
     *
     * @param sum the value for tb_donate.sum
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    public void setSum(Integer sum) {
        this.sum = sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_donate.origin
     *
     * @return the value of tb_donate.origin
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_donate.origin
     *
     * @param origin the value for tb_donate.origin
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    public void setOrigin(String origin) {
        this.origin = origin == null ? null : origin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_donate.last_order_id
     *
     * @return the value of tb_donate.last_order_id
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    public String getLastOrderId() {
        return lastOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_donate.last_order_id
     *
     * @param lastOrderId the value for tb_donate.last_order_id
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    public void setLastOrderId(String lastOrderId) {
        this.lastOrderId = lastOrderId == null ? null : lastOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_donate.last_donate_time
     *
     * @return the value of tb_donate.last_donate_time
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    public Date getLastDonateTime() {
        return lastDonateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_donate.last_donate_time
     *
     * @param lastDonateTime the value for tb_donate.last_donate_time
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    public void setLastDonateTime(Date lastDonateTime) {
        this.lastDonateTime = lastDonateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_donate.color_index
     *
     * @return the value of tb_donate.color_index
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    public Integer getColorIndex() {
        return colorIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_donate.color_index
     *
     * @param colorIndex the value for tb_donate.color_index
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    public void setColorIndex(Integer colorIndex) {
        this.colorIndex = colorIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_donate.name
     *
     * @return the value of tb_donate.name
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_donate.name
     *
     * @param name the value for tb_donate.name
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_donate.city
     *
     * @return the value of tb_donate.city
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_donate.city
     *
     * @param city the value for tb_donate.city
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }
}