package com.weather.passport.model;

import com.juzhai.core.dao.Limit;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DonateExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_donate
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_donate
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_donate
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    protected List<Criteria> oredCriteria;

    private Limit limit;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_donate
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    public DonateExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_donate
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_donate
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_donate
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_donate
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_donate
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_donate
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_donate
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_donate
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_donate
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_donate
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Limit limit) {
        this.limit = limit;
    }

    public Limit getLimit() {
        return this.limit;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_donate
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUdidIsNull() {
            addCriterion("udid is null");
            return (Criteria) this;
        }

        public Criteria andUdidIsNotNull() {
            addCriterion("udid is not null");
            return (Criteria) this;
        }

        public Criteria andUdidEqualTo(String value) {
            addCriterion("udid =", value, "udid");
            return (Criteria) this;
        }

        public Criteria andUdidNotEqualTo(String value) {
            addCriterion("udid <>", value, "udid");
            return (Criteria) this;
        }

        public Criteria andUdidGreaterThan(String value) {
            addCriterion("udid >", value, "udid");
            return (Criteria) this;
        }

        public Criteria andUdidGreaterThanOrEqualTo(String value) {
            addCriterion("udid >=", value, "udid");
            return (Criteria) this;
        }

        public Criteria andUdidLessThan(String value) {
            addCriterion("udid <", value, "udid");
            return (Criteria) this;
        }

        public Criteria andUdidLessThanOrEqualTo(String value) {
            addCriterion("udid <=", value, "udid");
            return (Criteria) this;
        }

        public Criteria andUdidLike(String value) {
            addCriterion("udid like", value, "udid");
            return (Criteria) this;
        }

        public Criteria andUdidNotLike(String value) {
            addCriterion("udid not like", value, "udid");
            return (Criteria) this;
        }

        public Criteria andUdidIn(List<String> values) {
            addCriterion("udid in", values, "udid");
            return (Criteria) this;
        }

        public Criteria andUdidNotIn(List<String> values) {
            addCriterion("udid not in", values, "udid");
            return (Criteria) this;
        }

        public Criteria andUdidBetween(String value1, String value2) {
            addCriterion("udid between", value1, value2, "udid");
            return (Criteria) this;
        }

        public Criteria andUdidNotBetween(String value1, String value2) {
            addCriterion("udid not between", value1, value2, "udid");
            return (Criteria) this;
        }

        public Criteria andSumIsNull() {
            addCriterion("sum is null");
            return (Criteria) this;
        }

        public Criteria andSumIsNotNull() {
            addCriterion("sum is not null");
            return (Criteria) this;
        }

        public Criteria andSumEqualTo(Integer value) {
            addCriterion("sum =", value, "sum");
            return (Criteria) this;
        }

        public Criteria andSumNotEqualTo(Integer value) {
            addCriterion("sum <>", value, "sum");
            return (Criteria) this;
        }

        public Criteria andSumGreaterThan(Integer value) {
            addCriterion("sum >", value, "sum");
            return (Criteria) this;
        }

        public Criteria andSumGreaterThanOrEqualTo(Integer value) {
            addCriterion("sum >=", value, "sum");
            return (Criteria) this;
        }

        public Criteria andSumLessThan(Integer value) {
            addCriterion("sum <", value, "sum");
            return (Criteria) this;
        }

        public Criteria andSumLessThanOrEqualTo(Integer value) {
            addCriterion("sum <=", value, "sum");
            return (Criteria) this;
        }

        public Criteria andSumIn(List<Integer> values) {
            addCriterion("sum in", values, "sum");
            return (Criteria) this;
        }

        public Criteria andSumNotIn(List<Integer> values) {
            addCriterion("sum not in", values, "sum");
            return (Criteria) this;
        }

        public Criteria andSumBetween(Integer value1, Integer value2) {
            addCriterion("sum between", value1, value2, "sum");
            return (Criteria) this;
        }

        public Criteria andSumNotBetween(Integer value1, Integer value2) {
            addCriterion("sum not between", value1, value2, "sum");
            return (Criteria) this;
        }

        public Criteria andOriginIsNull() {
            addCriterion("origin is null");
            return (Criteria) this;
        }

        public Criteria andOriginIsNotNull() {
            addCriterion("origin is not null");
            return (Criteria) this;
        }

        public Criteria andOriginEqualTo(String value) {
            addCriterion("origin =", value, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginNotEqualTo(String value) {
            addCriterion("origin <>", value, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginGreaterThan(String value) {
            addCriterion("origin >", value, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginGreaterThanOrEqualTo(String value) {
            addCriterion("origin >=", value, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginLessThan(String value) {
            addCriterion("origin <", value, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginLessThanOrEqualTo(String value) {
            addCriterion("origin <=", value, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginLike(String value) {
            addCriterion("origin like", value, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginNotLike(String value) {
            addCriterion("origin not like", value, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginIn(List<String> values) {
            addCriterion("origin in", values, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginNotIn(List<String> values) {
            addCriterion("origin not in", values, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginBetween(String value1, String value2) {
            addCriterion("origin between", value1, value2, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginNotBetween(String value1, String value2) {
            addCriterion("origin not between", value1, value2, "origin");
            return (Criteria) this;
        }

        public Criteria andLastOrderIdIsNull() {
            addCriterion("last_order_id is null");
            return (Criteria) this;
        }

        public Criteria andLastOrderIdIsNotNull() {
            addCriterion("last_order_id is not null");
            return (Criteria) this;
        }

        public Criteria andLastOrderIdEqualTo(String value) {
            addCriterion("last_order_id =", value, "lastOrderId");
            return (Criteria) this;
        }

        public Criteria andLastOrderIdNotEqualTo(String value) {
            addCriterion("last_order_id <>", value, "lastOrderId");
            return (Criteria) this;
        }

        public Criteria andLastOrderIdGreaterThan(String value) {
            addCriterion("last_order_id >", value, "lastOrderId");
            return (Criteria) this;
        }

        public Criteria andLastOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("last_order_id >=", value, "lastOrderId");
            return (Criteria) this;
        }

        public Criteria andLastOrderIdLessThan(String value) {
            addCriterion("last_order_id <", value, "lastOrderId");
            return (Criteria) this;
        }

        public Criteria andLastOrderIdLessThanOrEqualTo(String value) {
            addCriterion("last_order_id <=", value, "lastOrderId");
            return (Criteria) this;
        }

        public Criteria andLastOrderIdLike(String value) {
            addCriterion("last_order_id like", value, "lastOrderId");
            return (Criteria) this;
        }

        public Criteria andLastOrderIdNotLike(String value) {
            addCriterion("last_order_id not like", value, "lastOrderId");
            return (Criteria) this;
        }

        public Criteria andLastOrderIdIn(List<String> values) {
            addCriterion("last_order_id in", values, "lastOrderId");
            return (Criteria) this;
        }

        public Criteria andLastOrderIdNotIn(List<String> values) {
            addCriterion("last_order_id not in", values, "lastOrderId");
            return (Criteria) this;
        }

        public Criteria andLastOrderIdBetween(String value1, String value2) {
            addCriterion("last_order_id between", value1, value2, "lastOrderId");
            return (Criteria) this;
        }

        public Criteria andLastOrderIdNotBetween(String value1, String value2) {
            addCriterion("last_order_id not between", value1, value2, "lastOrderId");
            return (Criteria) this;
        }

        public Criteria andLastDonateTimeIsNull() {
            addCriterion("last_donate_time is null");
            return (Criteria) this;
        }

        public Criteria andLastDonateTimeIsNotNull() {
            addCriterion("last_donate_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastDonateTimeEqualTo(Date value) {
            addCriterion("last_donate_time =", value, "lastDonateTime");
            return (Criteria) this;
        }

        public Criteria andLastDonateTimeNotEqualTo(Date value) {
            addCriterion("last_donate_time <>", value, "lastDonateTime");
            return (Criteria) this;
        }

        public Criteria andLastDonateTimeGreaterThan(Date value) {
            addCriterion("last_donate_time >", value, "lastDonateTime");
            return (Criteria) this;
        }

        public Criteria andLastDonateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_donate_time >=", value, "lastDonateTime");
            return (Criteria) this;
        }

        public Criteria andLastDonateTimeLessThan(Date value) {
            addCriterion("last_donate_time <", value, "lastDonateTime");
            return (Criteria) this;
        }

        public Criteria andLastDonateTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_donate_time <=", value, "lastDonateTime");
            return (Criteria) this;
        }

        public Criteria andLastDonateTimeIn(List<Date> values) {
            addCriterion("last_donate_time in", values, "lastDonateTime");
            return (Criteria) this;
        }

        public Criteria andLastDonateTimeNotIn(List<Date> values) {
            addCriterion("last_donate_time not in", values, "lastDonateTime");
            return (Criteria) this;
        }

        public Criteria andLastDonateTimeBetween(Date value1, Date value2) {
            addCriterion("last_donate_time between", value1, value2, "lastDonateTime");
            return (Criteria) this;
        }

        public Criteria andLastDonateTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_donate_time not between", value1, value2, "lastDonateTime");
            return (Criteria) this;
        }

        public Criteria andColorIndexIsNull() {
            addCriterion("color_index is null");
            return (Criteria) this;
        }

        public Criteria andColorIndexIsNotNull() {
            addCriterion("color_index is not null");
            return (Criteria) this;
        }

        public Criteria andColorIndexEqualTo(Integer value) {
            addCriterion("color_index =", value, "colorIndex");
            return (Criteria) this;
        }

        public Criteria andColorIndexNotEqualTo(Integer value) {
            addCriterion("color_index <>", value, "colorIndex");
            return (Criteria) this;
        }

        public Criteria andColorIndexGreaterThan(Integer value) {
            addCriterion("color_index >", value, "colorIndex");
            return (Criteria) this;
        }

        public Criteria andColorIndexGreaterThanOrEqualTo(Integer value) {
            addCriterion("color_index >=", value, "colorIndex");
            return (Criteria) this;
        }

        public Criteria andColorIndexLessThan(Integer value) {
            addCriterion("color_index <", value, "colorIndex");
            return (Criteria) this;
        }

        public Criteria andColorIndexLessThanOrEqualTo(Integer value) {
            addCriterion("color_index <=", value, "colorIndex");
            return (Criteria) this;
        }

        public Criteria andColorIndexIn(List<Integer> values) {
            addCriterion("color_index in", values, "colorIndex");
            return (Criteria) this;
        }

        public Criteria andColorIndexNotIn(List<Integer> values) {
            addCriterion("color_index not in", values, "colorIndex");
            return (Criteria) this;
        }

        public Criteria andColorIndexBetween(Integer value1, Integer value2) {
            addCriterion("color_index between", value1, value2, "colorIndex");
            return (Criteria) this;
        }

        public Criteria andColorIndexNotBetween(Integer value1, Integer value2) {
            addCriterion("color_index not between", value1, value2, "colorIndex");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_donate
     *
     * @mbggenerated do_not_delete_during_merge Fri Dec 13 13:51:54 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_donate
     *
     * @mbggenerated Fri Dec 13 13:51:54 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}