package com.weather.passport.model;

import java.io.Serializable;
import java.util.Date;

public class Order implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.order_id
     *
     * @mbggenerated Tue Dec 17 12:50:19 CST 2013
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.udid
     *
     * @mbggenerated Tue Dec 17 12:50:19 CST 2013
     */
    private String udid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.origin
     *
     * @mbggenerated Tue Dec 17 12:50:19 CST 2013
     */
    private String origin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.create_time
     *
     * @mbggenerated Tue Dec 17 12:50:19 CST 2013
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.price
     *
     * @mbggenerated Tue Dec 17 12:50:19 CST 2013
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_order
     *
     * @mbggenerated Tue Dec 17 12:50:19 CST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.order_id
     *
     * @return the value of tb_order.order_id
     *
     * @mbggenerated Tue Dec 17 12:50:19 CST 2013
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.order_id
     *
     * @param orderId the value for tb_order.order_id
     *
     * @mbggenerated Tue Dec 17 12:50:19 CST 2013
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.udid
     *
     * @return the value of tb_order.udid
     *
     * @mbggenerated Tue Dec 17 12:50:19 CST 2013
     */
    public String getUdid() {
        return udid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.udid
     *
     * @param udid the value for tb_order.udid
     *
     * @mbggenerated Tue Dec 17 12:50:19 CST 2013
     */
    public void setUdid(String udid) {
        this.udid = udid == null ? null : udid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.origin
     *
     * @return the value of tb_order.origin
     *
     * @mbggenerated Tue Dec 17 12:50:19 CST 2013
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.origin
     *
     * @param origin the value for tb_order.origin
     *
     * @mbggenerated Tue Dec 17 12:50:19 CST 2013
     */
    public void setOrigin(String origin) {
        this.origin = origin == null ? null : origin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.create_time
     *
     * @return the value of tb_order.create_time
     *
     * @mbggenerated Tue Dec 17 12:50:19 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.create_time
     *
     * @param createTime the value for tb_order.create_time
     *
     * @mbggenerated Tue Dec 17 12:50:19 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.price
     *
     * @return the value of tb_order.price
     *
     * @mbggenerated Tue Dec 17 12:50:19 CST 2013
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.price
     *
     * @param price the value for tb_order.price
     *
     * @mbggenerated Tue Dec 17 12:50:19 CST 2013
     */
    public void setPrice(Integer price) {
        this.price = price;
    }
}